---
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: express-server
    container_name: express-server
    command: npm run dev
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5555:5555
    depends_on:
      - mongo
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network

  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - 27017:27017
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: react-client
    container_name: react-client
    command: npm run dev
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - 5173:5173
    networks:
      - app-network


networks:
  app-network:
    driver: bridge


volumes:
  data-volume: null
  node_modules: null
  web-root:
    driver: local